version: '3'
services:
    producer:
        build: producer
        environment:
            - KAFKA_BROKER=192.168.99.100:9092
            - KAFKA_TOPIC=test
    consumer:
        build: consumer
        environment:
            - KAFKA_BROKER=192.168.99.100:9092
            - KAFKA_TOPIC=test
        depends_on:
            - producer